---
deployment:
  tasks:
    - export DEPLOYPATH=/home/doableda/public_html/
    - /bin/cp dist\spa\css $DEPLOYPATH
    - /bin/cp dist\spa\fonts $DEPLOYPATH
    - /bin/cp dist\spa\icons $DEPLOYPATH
    - /bin/cp dist\spa\img $DEPLOYPATH
    - /bin/cp dist\spa\js $DEPLOYPATH
    - /bin/cp dist\spa\favicon.ico $DEPLOYPATH
    - /bin/cp dist\spa\index.html $DEPLOYPATH